[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
lazy_static = "1.5"
regex = "1.11"
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

[lib]
path = "Source/lib.rs"

[package]
edition = "2018"
name = "doc-scraper"
version = "0.1.0"
# select = "0.5.0"
