[package]
name = "doc-scraper"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
clap = { version = "3.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
anyhow = { version = "1.0" }
scraper = { version = "0.12" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
regex = { version = "1.5" }
lazy_static = { version = "1.4" }
# select = "0.5.0"
